# Generated by Django 3.2.6 on 2022-07-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comunicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicacao',
            options={'verbose_name': 'Comunicações', 'verbose_name_plural': 'Comunicações'},
        ),
    ]
