# Generated by Django 3.2.6 on 2022-07-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comunicacao_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicacao',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='comunicacao',
            name='criados',
        ),
        migrations.RemoveField(
            model_name='comunicacao',
            name='modificado',
        ),
    ]
